### PR TITLE
Rich text team intro

### LINKED ISSUE #339: Remove old team page functionality
Passing team id to general learning circle search pages doesn't work as expected.

image

See [lapl](https://www.p2pu.org/en/learning-circles/?team_id=22&team=Los%20Angeles%20Public%20Library)

- Remove team title functionality based on query param

### PR DESCRIPTION
**Pull request by s-kennedy**
Screen Shot 2020-06-24 at 2 23 08 PM

- use formatted text
- update team page with data from API
- fix some weirdness with logo and image styles
- fixes #339 

Here are the instructions for organizers on updating their team page: 
https://docs.google.com/document/d/1v1hKUYSYLpal6SqeAliC_HcuAYwFRl8Iy8KHIFpCbPk/edit#heading=h.u0j8kcn6w9dp

### CODE REVIEW

File: assets/react/search.jsx [hunk 1]
```diff
@@ -7,14 +7,8 @@ import 'p2pu-search-cards/dist/build.css';
...
 let elem = document.getElementById('search-lc-component');
 
-let initialState = {}
-if (elem.dataset.teamId) {
-  initialState["team_id"] = elem.dataset.teamId
-}
-
 ReactDOM.render(
   <Search
-    initialState={initialState}
```
Comment (dirkcuys) [inline assets/react/search.jsx:17]: @s-kennedy this isn't the old search page functionality, this is how the search is scoped by team_id. See [this commit](https://github.com/p2pu/p2pu-website/commit/2cb6de4e407c73c293488890a7c1e0c9cc483009#diff-c752d1a02f7a56eb6f0caf3628086f8b).

Unless you update the search component after that to otherwise get the team ID, I think this will break the search on team pages.

Comment (s-kennedy) [reply assets/react/search.jsx]: ha this is a true face palm moment.

**Comment by s-kennedy** [comment]
@dirkcuys so I tried to make sure all the fields can be updated or added, i.e. even if the field is empty, the template will still render an element with an ID so that if the team updates that field the script will have somewhere to add the new content. The  caveat is that it becomes tricky if they want to delete fields. The header image and intro text have default content in the template, so we'd have to recreate and append those elements in the script, but everything else is hidden if there's no content. It was getting too messy so I decided to scrap that approach and leave it that if the incoming field from the API is empty, we do nothing, otherwise, we update if it's different from what's already in the template. I added this caveat to the [doc](https://docs.google.com/document/d/1v1hKUYSYLpal6SqeAliC_HcuAYwFRl8Iy8KHIFpCbPk/edit#).
